language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk6
script:
- cd src/main/java
- javac *.java
- java RouterCheck simpleTests.csv
- java RouterCheck difficultTests.csv
- java RouterCheck sampleTests.csv
- cd ..
- cd ..
- cd ..
- mvn test
