language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk6
script:
- cd src
- javac *.java
- java RouterCheck simpleTests.csv
- java RouterCheck difficultTests.csv
- java RouterCheck sampleTests.csv

-cd ..
- mvn tests
