language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk6
script:
- cd src
- javac *.java
- java RouterCheck simpleTest.csv
- java RouterCheck difficultTest.csv
- java RouterCheck sample.csv

- cd ..
- cd tests
- javac JUnitTests.java
- java JUnitTests
